# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-27 06:25
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('common', '0010_competitionpage_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionpage',
            name='map_description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_map_description', slotname='map_description', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='competitionpage',
            name='map_extra',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_map_extra', slotname='map_extra', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='common_activity', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='common_homeslide', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
