# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceclub', '0058_auto_20170927_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancer',
            name='social',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
